// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGEIabPpcCpEjlb-K2_QJPQ73kFYTOzio',
    appId: '1:853447844228:web:69a2700a6b73f78fbd7dd1',
    messagingSenderId: '853447844228',
    projectId: 'frit-hub',
    authDomain: 'frit-hub.firebaseapp.com',
    storageBucket: 'frit-hub.firebasestorage.app',
    measurementId: 'G-1Z0LRRP82D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9ymocfJAyNsoHIkxsNvKg6VPn59tsZhM',
    appId: '1:853447844228:android:3bfbdaeb34b60aa0bd7dd1',
    messagingSenderId: '853447844228',
    projectId: 'frit-hub',
    storageBucket: 'frit-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxctKyfB2zZjdfXMdvFQjg_eV-wbBLClA',
    appId: '1:853447844228:ios:171aaf6f49413a11bd7dd1',
    messagingSenderId: '853447844228',
    projectId: 'frit-hub',
    storageBucket: 'frit-hub.firebasestorage.app',
    androidClientId: '853447844228-j1m05kspqt1vcc08psr5uqst478plfuc.apps.googleusercontent.com',
    iosClientId: '853447844228-j9vr4ino5dtukh4s8o5i63id1sn76gf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubBashbord',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxctKyfB2zZjdfXMdvFQjg_eV-wbBLClA',
    appId: '1:853447844228:ios:171aaf6f49413a11bd7dd1',
    messagingSenderId: '853447844228',
    projectId: 'frit-hub',
    storageBucket: 'frit-hub.firebasestorage.app',
    androidClientId: '853447844228-j1m05kspqt1vcc08psr5uqst478plfuc.apps.googleusercontent.com',
    iosClientId: '853447844228-j9vr4ino5dtukh4s8o5i63id1sn76gf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubBashbord',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGEIabPpcCpEjlb-K2_QJPQ73kFYTOzio',
    appId: '1:853447844228:web:5a18c66c7dccf9f0bd7dd1',
    messagingSenderId: '853447844228',
    projectId: 'frit-hub',
    authDomain: 'frit-hub.firebaseapp.com',
    storageBucket: 'frit-hub.firebasestorage.app',
    measurementId: 'G-4XXNR0QHGT',
  );
}
